import { makeStyles } from '@material-ui/core/styles';

export default makeStyles(() => ({
    root: {
        maxWidth: '100%',
        textAlign: 'center',


    },
    media: {
        height: '120px',
        paddingTop: '70%', //16:9
    },
    cardActions: {
        display: 'flex',
        justifyContent: 'flex-end',
        height: '0%',
        margin: '0%',

    },
    cardContent: {
        // display: 'flex',
        textAlign: 'center',
        justifyContent: 'space-between',
        height: '0%',
        margin: '0%',
    },
    titleProduct: {
        display: 'block',
        position: 'relative',
        fontFamily: 'Hind,sans-serif',
        color: '#191919',
        marginBottom: '0',
        fontSize: '20px',
        lineHeight: '40px',
        fontWeight: '500',
        marginTop: '19px',
        color: '#191919',
        textAlign: 'center',

    },
    subTitle: {
        textAlign: 'center',
        color: '#191919',
        fontFamily: 'Hind,sans-serif',
        fontSize: '14px',
        lineHeight: '22px',
        fontWeight: '300',
    },
    priceProduct: {
        display: 'block',
        position: 'relative',
        fontFamily: 'Hind,sans-serif',
        color: '#191919',
        marginBottom: '0',
        fontSize: '20px',
        lineHeight: '40px',
        fontWeight: '500',
        marginTop: '19px',
        color: '#191919',
    },
    box: {

        "WebkitTextSizeAdjust": "100%",
        "WebkitTapHighlightColor": "rgba(0,0,0,0)",
        "-blue": "#007bff",
        "-indigo": "#6610f2",
        "-purple": "#6f42c1",
        "-pink": "#e83e8c",
        "-red": "#dc3545",
        "-orange": "#fd7e14",
        "-yellow": "#ffc107",
        "-green": "#28a745",
        "-teal": "#20c997",
        "-cyan": "#17a2b8",
        "-white": "#fff",
        "-gray": "#6c757d",
        "-grayDark": "#343a40",
        "-primary": "#007bff",
        "-secondary": "#6c757d",
        "-success": "#28a745",
        "-info": "#17a2b8",
        "-warning": "#ffc107",
        "-danger": "#dc3545",
        "-light": "#f8f9fa",
        "-dark": "#343a40",
        "-breakpointXs": "0",
        "-breakpointSm": "576px",
        "-breakpointMd": "791px",
        "-breakpointLg": "1025px",
        "-breakpointXl": "1230px",
        "-fontFamilySansSerif": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",\"Liberation Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\"",
        "-fontFamilyMonospace": "SFMono-Regular,Menlo,Monaco,Consolas,\"Liberation Mono\",\"Courier New\",monospace",
        "textAlign": "left",
        "fontSize": "14px",
        "lineHeight": "22px",
        "fontWeight": "300",
        "color": "#777",
        "direction": "ltr",
        "fontFamily": "Roboto,sans-serif",
        "boxSizing": "border-box",
        "position": "relative",
        "width": "100%",
        "paddingRight": "10px",
        "paddingLeft": "10px",
        "flex": "0 0 25%",
        "maxWidth": "25%"
    },
    ttproduct: {

        "WebkitTextSizeAdjust": "100%",
        "WebkitTapHighlightColor": "rgba(0,0,0,0)",
        "-blue": "#007bff",
        "-indigo": "#6610f2",
        "-purple": "#6f42c1",
        "-pink": "#e83e8c",
        "-red": "#dc3545",
        "-orange": "#fd7e14",
        "-yellow": "#ffc107",
        "-green": "#28a745",
        "-teal": "#20c997",
        "-cyan": "#17a2b8",
        "-white": "#fff",
        "-gray": "#6c757d",
        "-grayDark": "#343a40",
        "-primary": "#007bff",
        "-secondary": "#6c757d",
        "-success": "#28a745",
        "-info": "#17a2b8",
        "-warning": "#ffc107",
        "-danger": "#dc3545",
        "-light": "#f8f9fa",
        "-dark": "#343a40",
        "-breakpointXs": "0",
        "-breakpointSm": "576px",
        "-breakpointMd": "791px",
        "-breakpointLg": "1025px",
        "-breakpointXl": "1230px",
        "-fontFamilySansSerif": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",\"Liberation Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\"",
        "-fontFamilyMonospace": "SFMono-Regular,Menlo,Monaco,Consolas,\"Liberation Mono\",\"Courier New\",monospace",
        "textAlign": "left",
        "fontSize": "14px",
        "lineHeight": "22px",
        "fontWeight": "300",
        "color": "#777",
        "direction": "ltr",
        "fontFamily": "Roboto,sans-serif",
        "boxSizing": "border-box",
        "position": "relative",
        "width": "100%",
        "paddingRight": "10px",
        "paddingLeft": "10px",
        "flex": "0 0 25%",
        "maxWidth": "25%"
    },
    imagebox: {

        "WebkitTextSizeAdjust": "100%",
        "WebkitTapHighlightColor": "rgba(0,0,0,0)",
        "-blue": "#007bff",
        "-indigo": "#6610f2",
        "-purple": "#6f42c1",
        "-pink": "#e83e8c",
        "-red": "#dc3545",
        "-orange": "#fd7e14",
        "-yellow": "#ffc107",
        "-green": "#28a745",
        "-teal": "#20c997",
        "-cyan": "#17a2b8",
        "-white": "#fff",
        "-gray": "#6c757d",
        "-grayDark": "#343a40",
        "-primary": "#007bff",
        "-secondary": "#6c757d",
        "-success": "#28a745",
        "-info": "#17a2b8",
        "-warning": "#ffc107",
        "-danger": "#dc3545",
        "-light": "#f8f9fa",
        "-dark": "#343a40",
        "-breakpointXs": "0",
        "-breakpointSm": "576px",
        "-breakpointMd": "791px",
        "-breakpointLg": "1025px",
        "-breakpointXl": "1230px",
        "-fontFamilySansSerif": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",\"Liberation Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\"",
        "-fontFamilyMonospace": "SFMono-Regular,Menlo,Monaco,Consolas,\"Liberation Mono\",\"Courier New\",monospace",
        "fontSize": "14px",
        "lineHeight": "22px",
        "fontWeight": "300",
        "color": "#777",
        "direction": "ltr",
        "fontFamily": "Roboto,sans-serif",
        "textAlign": "left!important",
        "boxSizing": "border-box",
        "position": "relative",
        "marginTop": "0"

    },
    ttimg: {
        "WebkitTextSizeAdjust": "100%",
        "WebkitTapHighlightColor": "rgba(0,0,0,0)",
        "-blue": "#007bff",
        "-indigo": "#6610f2",
        "-purple": "#6f42c1",
        "-pink": "#e83e8c",
        "-red": "#dc3545",
        "-orange": "#fd7e14",
        "-yellow": "#ffc107",
        "-green": "#28a745",
        "-teal": "#20c997",
        "-cyan": "#17a2b8",
        "-white": "#fff",
        "-gray": "#6c757d",
        "-grayDark": "#343a40",
        "-primary": "#007bff",
        "-secondary": "#6c757d",
        "-success": "#28a745",
        "-info": "#17a2b8",
        "-warning": "#ffc107",
        "-danger": "#dc3545",
        "-light": "#f8f9fa",
        "-dark": "#343a40",
        "-breakpointXs": "0",
        "-breakpointSm": "576px",
        "-breakpointMd": "791px",
        "-breakpointLg": "1025px",
        "-breakpointXl": "1230px",
        "-fontFamilySansSerif": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",\"Liberation Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\"",
        "-fontFamilyMonospace": "SFMono-Regular,Menlo,Monaco,Consolas,\"Liberation Mono\",\"Courier New\",monospace",
        "fontSize": "14px",
        "lineHeight": "22px",
        "fontWeight": "300",
        "direction": "ltr",
        "fontFamily": "Roboto,sans-serif",
        "textAlign": "left!important",
        "color": "#777",
        "boxSizing": "border-box"
    },
    productimg: {
        "WebkitTextSizeAdjust": "100%",
        "WebkitTapHighlightColor": "rgba(0,0,0,0)",
        "-blue": "#007bff",
        "-indigo": "#6610f2",
        "-purple": "#6f42c1",
        "-pink": "#e83e8c",
        "-red": "#dc3545",
        "-orange": "#fd7e14",
        "-yellow": "#ffc107",
        "-green": "#28a745",
        "-teal": "#20c997",
        "-cyan": "#17a2b8",
        "-white": "#fff",
        "-gray": "#6c757d",
        "-grayDark": "#343a40",
        "-primary": "#007bff",
        "-secondary": "#6c757d",
        "-success": "#28a745",
        "-info": "#17a2b8",
        "-warning": "#ffc107",
        "-danger": "#dc3545",
        "-light": "#f8f9fa",
        "-dark": "#343a40",
        "-breakpointXs": "0",
        "-breakpointSm": "576px",
        "-breakpointMd": "791px",
        "-breakpointLg": "1025px",
        "-breakpointXl": "1230px",
        "-fontFamilySansSerif": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",\"Liberation Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\"",
        "-fontFamilyMonospace": "SFMono-Regular,Menlo,Monaco,Consolas,\"Liberation Mono\",\"Courier New\",monospace",
        "fontSize": "14px",
        "lineHeight": "22px",
        "fontWeight": "300",
        "direction": "ltr",
        "fontFamily": "Roboto,sans-serif",
        "textAlign": "left!important",
        "color": "#777",
        "boxSizing": "border-box"
    }

}));