import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  toolbar: theme.mixins.toolbar,
  title: {

    textAlign: 'center',
    marginTop: '5%',
    position: 'relative',
    textDecoration: 'none',
    display: 'block',
    fontFamily: 'Hind,sans-serif',
    color: '#191919',
    fontSize: '25px',
    lineHeight: '44px',
    fontWeight: '500',
    color: '#191919',
  },
  desciption: {
    marginTop: '10px',
    fontSize: '14px',
    lineHeight: '22px',
    fontWeight: '300',
    color: '#777',

  },
  divStyle: {
    overflowY: 'scroll',
    border: '0.5px solid grey',
    width: '500px',
    float: 'left',
    height: '200px',
    position: 'relative',
    fontSize: '12px',

  },
  requiredFields: {
    "textAlign": "left",
    "fontFamily": "Hind,sans-serif",
    "fontSize": "14px",
    "lineHeight": "22px",
    "fontWeight": "300",
    "direction": "ltr",
    "boxSizing": "border-box",
    "display": "inline-block",
    "float": "right",
    "color": "#777",
    "paddingLeft": "5px"
  },
  message: {
    "textAlign": "left",
    "fontFamily": "Hind,sans-serif",
    "fontSize": "12px",
    "lineHeight": "22px",
    "fontWeight": "300",
    "direction": "ltr",
    "boxSizing": "border-box",
    "display": "inline-block",
    "color": "#0093B1",
    "padding": "5px"
  },
  message3: {
    "textAlign": "left",
    "fontFamily": "Hind,sans-serif",
    "fontSize": "12px",
    "lineHeight": "22px",
    "fontWeight": "300",
    "direction": "ltr",
    "boxSizing": "border-box",
    "display": "inline-block",
    "color": "#646464",
    "padding": "5px"
  },
  crossButton:{
    textDecoration: "none",
    background: "none",
    border: "none",
    color: 'grey',

    '&:hover': {
      color: '#000000',
      outline: 'none',

    },
  },
  membershipTerms: {
    "textAlign": "left",
    "fontFamily": "Hind,sans-serif",
    "fontSize": "12px",
    "lineHeight": "22px",
    "fontWeight": "300",
    "direction": "ltr",
    "boxSizing": "border-box",
    "display": "inline-block",
    "color": "#646464",
    "padding": "5px",
    textDecoration: "none",
    background: "none",
    border: "none",
    textDecorationLine: 'underline',
    '&:hover': {
      color: '#000000',
      outline: 'none',

    },
  },
  message2: {
    "textAlign": "left",
    "fontFamily": "Hind,sans-serif",
    "fontSize": "12px",
    "lineHeight": "22px",
    "fontWeight": "300",
    "direction": "ltr",
    "boxSizing": "border-box",
    "display": "inline-block",
    "color": "#000000",
    // "paddingLeft": "5px",
    "padding": "20px"
  },
  formGroup: {
    "textAlign": "left",
    "lineHeight": "22px",
    "direction": "ltr",
    "boxSizing": "border-box",
    "marginBottom": "5%",
    "fontSize": "14px",
    "color": "#191919",
    "fontFamily": "Hind,sans-serif",
    "fontWeight": "500",
    "paddingTop": "10px",
    "letterSpacing": ".02em"
  },
  formControl: {
    "direction": "ltr",
    "boxSizing": "border-box",
    "margin": "0",
    "overflow": "visible",
    "display": "block",
    "width": "100%",
    "background": "#f7f8fa",
    "fontSize": "14px",
    "border": "1px solid #f7f8fa",
    "padding": "11px 12px 10px 15px",
    "fontFamily": "Hind,sans-serif",
    "boxShadow": "none",
    "outline": "none",
    "color": "#777",
    "fontWeight": "300",
    "borderRadius": "6px",
    "transition": "all .2s linear",
    "height": "40px",
    "WebkitAppearance": "none",
    "paddingTop": "3px",
    "paddingBottom": "1px",
    "lineHeight": "2.9"
  },
  subTitle: {
    "textAlign": "left",
    "direction": "ltr",
    "boxSizing": "border-box",
    "marginTop": "0",
    "display": "block",
    "position": "relative",
    "fontFamily": "Hind,sans-serif",
    "color": "#191919",
    "marginBottom": "0",
    "fontSize": "20px",
    "lineHeight": "30px",
    "padding": "0 0 14px",
    "fontWeight": "500"
  },
  form: {
    "textAlign": "left",
    "fontFamily": "Hind,sans-serif",
    "fontSize": "14px",
    "lineHeight": "22px",
    "fontWeight": "300",
    "color": "#777",
    "direction": "ltr",
    "boxSizing": "border-box",
    "display": "flex",
    "flexDirection": "column",
    "flexWrap": "nowrap",
    "justifyContent": "flex-start",
    "alignContent": "stretch",
    "alignItems": "stretch"
  },
  additionalLinks: {
    "fontSize": "14px",
    "lineHeight": "22px",
    "fontWeight": "300",
    "direction": "ltr",
    "listStyle": "none",
    "boxSizing": "border-box",
    "backgroundColor": "transparent",
    "textDecoration": "none",
    "outline": "none",
    "color": "#2879fe",
    "transition": "all .2s linear",
    "textAlign": "left",
    "fontFamily": "Hind,sans-serif",
    "fontSize": "14px",
    "lineHeight": "22px",
    "fontWeight": "300",
    "direction": "ltr",
    "boxSizing": "border-box",
    "display": "inline-block",
    "color": "#777",
  },
  bigcontainer: {
    background: 'white',

  },
  container: {
    borderTopWidth: '1px',
    // borderTopStyle: 'solid',
    padding: '0px',
    "color": "#777",
    "boxSizing": "border-box",
    background: 'white',

    fontFamily: 'Hind,sans-serif',
    fontSize: '20px',
    // marginTop: '14%',
    display: 'flex',
    flexDirection: 'row',
    // backgroundColor: 'red',
    justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: 'white',
  },
  leftBox: {
    flexDirection: 'row',
    backgroundColor: 'white',
    padding: '5px',
    width: '50%',
    padding: '5%',
    borderColor: 'grey',
    borderWidth: '1px',
    borderStyle: 'solid',
    margin: '1%',

  },
  rightBox: {
    justifyContent: 'center',
    backgroundColor: 'white',
    padding: '5px',
    width: '50%',
    margin: '1%',
    padding: '5%',
    borderColor: 'grey',
    borderWidth: '1px',
    borderStyle: 'solid',
  },

  box1: {
    textAlign: 'center',
    margin: '250px',
    marginTop: '30px',
    marginBottom: '30px',
    display: 'flex',
    background: 'white',
    padding: '10px',
  },

  button: {
    margin: '5px',
    background: 'transparent',
    color: '#2879fe',
    border: '2px solid #2879fe',
    height: '40px',
    paddingLeft: '29px',
    paddingRight: '29px',
    fontSize: '14px',
    fontWeight: '400',
    letterSpacing: '.03em',
    borderRadius: '6px',
    '&:hover': {
      backgroundColor: '#191919',
      color: '#fff',
      borderColor: '#191919',
      outline: 'none',

    },
  },
  emptyButton: {
    minWidth: '150px',
    [theme.breakpoints.down('xs')]: {
      marginBottom: '5px',
    },
    [theme.breakpoints.up('xs')]: {
      marginRight: '20px',
    },
  },
  checkoutButton: {
    minWidth: '150px',
  },
  link: {
    textDecoration: 'none',
  },
  cardDetails: {
    display: 'flex',
    marginTop: '10%',
    width: '100%',
    justifyContent: 'space-between',
  },
}));